version: '3'

services:
  mysql-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_DATABASE: scbj

  redis-container:
    image: redis:latest
    ports:
      - "6379:6379"
