spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_URL}:${PROD_MYSQL_PORT}/scbj?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}


  data:
    redis:
      host: ${PROD_REDIS_URL}
      port: ${PROD_REDIS_PORT}

jwt:
  secret: KF81YSUjd3Q3KCFfaXd6cHlwMyNAKitkamFtYj02OXh2X3JfN2sqZShyamQrZysoXzVhJSN3dDcoIV9pd3pweXAzI0AqK2RqYW1iPTY5eHZfcl83ayplKHJqZCtnKw==   # Replace with your actual secret key
  expiration: 3600000       # Replace with your desired expiration time in milliseconds
  refreshExpiration: 604800000 # Replace with your desired refresh expiration time in milliseconds
  redisRefreshKeyPrefix: "Refresh-token:" # Replace with your desired Redis refresh key prefix

